### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-kviz-app#10]
Change the entire font of the website to something more appealing

**Comment by RidhiChhajer** [comment]
Can you provide the description, what font to be changed where. Im interested

**Comment by Sheetal-05** [comment]
Please assign this issue to me.

**Comment by Alcyone713** [comment]
> Can you provide the description, what font to be changed where. Im interested

Please add a screenshot in you PR comment or here so I can see what the changes look like.

**Comment by RidhiChhajer** [comment]
done

**Comment by sarasiddiquie** [comment]
Please assign this issue to me .

**Comment by Neetika146** [comment]
please assign this issue to me.

**Comment by captain-sal** [comment]
Please assign this issue to me.

**Comment by BhavyaDevani** [comment]
@Alcyone713 pls assign this issue to me
