### ISSUE TITLE
Add a dark theme option

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-kviz-app#2]

**Comment by karishma-2020** [comment]
@Alcyone713 

please assign me this issue

**Comment by s-bhatla** [comment]
Please assign me this issue.

**Comment by captain-sal** [comment]
Please assign this issue.

**Comment by BhavyaDevani** [comment]
@Alcyone713 pls assign this issue to me

**Comment by Alcyone713** [comment]
I am assigning everyone the issue, but I'll only merge the best PR.

**Comment by soumyajindal0707** [comment]
pls assign this issue to me, I think I know the solution. Have already solved it according to it

**Comment by BhavyaDevani** [comment]
@Alcyone713 I have created a PR to fix this issue. Kindly review it and do let me know if any other changes are required

**Comment by ShubhaSwarup** [comment]
please assign this issue to me
