### ISSUE TITLE
Enhance mobile responsiveness

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-kviz-app#3]

**Comment by Aakriti-malla** [comment]
Hey! I can enhance the website's mobile responsiveness. Kindly assign this issue to me

**Comment by RidhiChhajer** [comment]
if this issue is yet to be resolved, kindly assign this to me

**Comment by iamatifmoin** [comment]
@Alcyone713 
I have resolved the issue.
Please review the PR.
