### ISSUE TITLE
Add sounds for right and wrong answers

### ISSUE THREAD

**Issue by Alcyone713** [GDSC-IGDTUW-Autumn-of-Code-2022/webD-kviz-app#4]

**Comment by Aakriti-malla** [comment]
Hey! I would like to work on this issue, Kindly assign me this!

**Comment by AasthaSinghal21** [comment]
Hey! I would like to work on this issue. Please assign me this.

**Comment by Aakriti-malla** [comment]
@Alcyone713 Hey! I added the sounds under the sound folder, wrote the code and created a Pull Request for the same! Do Check.
